
##############################
#
#  Global Variables
#
##############################

global CONSUMER_KEY
global CONSUMER_SECRET
global ACCESS_TOKEN
global ACCESS_SECRET

global CURRENT_USER_ID

###
### TWITTER API KEY
###
CONSUMER_KEY = '[REMOVED FROM SUBMISSION FOR SECURITY REASON]'
CONSUMER_SECRET = '[REMOVED FROM SUBMISSION FOR SECURITY REASON]'
ACCESS_TOKEN = '[REMOVED FROM SUBMISSION FOR SECURITY REASON]'
ACCESS_SECRET = '[REMOVED FROM SUBMISSION FOR SECURITY REASON]'

CURRENT_USER_ID = '[REMOVED FROM SUBMISSION FOR SECURITY REASON]' # SET TO BOT

###
### AWS FUNCTIONALITY
###
REGION_NAME = 'ap-southeast-1'
ENDPOINT_URL = 'https://dynamodb.ap-southeast-1.amazonaws.com/' #'http://localhost:8000'
